clear all; close all; clc;

%% PPG
load ../../Results/resultSucForPPGcompMeth ;
fprintf('===============================\n')
fprintf('             PPG               \n')
fprintf('===============================\n')

fprintf('===================Forecasting Performance======================\n')
fprintf(' ______________________________________________________________\n')
fprintf('| Extension Method | Computing time (sec.) | Forecasting Error |\n')
fprintf('|------------------|-----------------------|-------------------|\n')
fprintf('|      LSE         |           %.2f        |     %.3e     |\n', CompTime1.LSE , mean(forecastErr1.LSE))
fprintf('|      EDMD        |           %.2f        |     %.3e     |\n', CompTime1.EDMD , mean(forecastErr1.EDMD))
fprintf('|      GPR         |         %.2f        |     %.3e     |\n', CompTime1.GPR , mean(forecastErr1.GPR))
fprintf('|__________________|_______________________|___________________|\n\n')


fprintf('==============SST==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.sst.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.sst.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.sst.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.sst.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('=============STFT==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.stft.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.stft.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.stft.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.stft.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('==============RS===============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD2.rs.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD2.rs.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD2.rs.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD2.rs.GPR))
fprintf('|__________________|___________|\n\n')

%% THO
load ../../Results/resultSucForTHOcompMeth ;
fprintf('===============================\n')
fprintf('              THO              \n')
fprintf('===============================\n')

fprintf('===================Forecasting Performance======================\n')
fprintf(' ______________________________________________________________\n')
fprintf('| Extension Method | Computing time (sec.) | Forecasting Error |\n')
fprintf('|------------------|-----------------------|-------------------|\n')
fprintf('|      LSE         |           %.2f        |     %.3e     |\n', CompTime1.LSE , mean(forecastErr1.LSE))
fprintf('|      EDMD        |           %.2f        |     %.3e     |\n', CompTime1.EDMD , mean(forecastErr1.EDMD))
fprintf('|      GPR         |          %.2f        |     %.3e     |\n', CompTime1.GPR , mean(forecastErr1.GPR))
fprintf('|__________________|_______________________|___________________|\n\n')

fprintf('==============SST==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.sst.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.sst.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.sst.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.sst.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('=============STFT==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.stft.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.stft.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.stft.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.stft.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('==============RS===============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD2.rs.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD2.rs.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD2.rs.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD2.rs.GPR))
fprintf('|__________________|___________|\n\n')

%% EEG
load ../../Results/resultSucForEEGcompMeth ;
fprintf('===============================\n')
fprintf('              EEG              \n')
fprintf('===============================\n')

fprintf('===================Forecasting Performance======================\n')
fprintf(' ______________________________________________________________\n')
fprintf('| Extension Method | Computing time (sec.) | Forecasting Error |\n')
fprintf('|------------------|-----------------------|-------------------|\n')
fprintf('|      LSE         |           %.2f        |     %.3e     |\n', CompTime1.LSE , mean(forecastErr1.LSE))
fprintf('|      EDMD        |           %.2f        |     %.3e     |\n', CompTime1.EDMD , mean(forecastErr1.EDMD))
fprintf('|      GPR         |          %.2f        |     %.3e     |\n', CompTime1.GPR , mean(forecastErr1.GPR))
fprintf('|__________________|_______________________|___________________|\n\n')

fprintf('==============SST==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.sst.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.sst.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.sst.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.sst.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('=============STFT==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.stft.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.stft.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.stft.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.stft.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('==============RS===============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD2.rs.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD2.rs.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD2.rs.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD2.rs.GPR))
fprintf('|__________________|___________|\n\n')

%% ECG
load ../../Results/resultSucForECGcompMeth ;
fprintf('===============================\n')
fprintf('              ECG              \n')
fprintf('===============================\n')

fprintf('===================Forecasting Performance======================\n')
fprintf(' ______________________________________________________________\n')
fprintf('| Extension Method | Computing time (sec.) | Forecasting Error |\n')
fprintf('|------------------|-----------------------|-------------------|\n')
fprintf('|      LSE         |           %.2f        |     %.3e     |\n', CompTime1.LSE , mean(forecastErr1.LSE))
fprintf('|      EDMD        |          %.2f        |     %.3e     |\n', CompTime1.EDMD , mean(forecastErr1.EDMD))
fprintf('|      GPR         |         %.2f        |     %.3e     |\n', CompTime1.GPR , mean(forecastErr1.GPR))
fprintf('|__________________|_______________________|___________________|\n\n')

fprintf('==============SST==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.sst.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.sst.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.sst.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.sst.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('=============STFT==============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD1.stft.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD1.stft.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD1.stft.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD1.stft.GPR))
fprintf('|__________________|___________|\n\n')

fprintf('==============RS===============\n')
fprintf(' ______________________________\n')
fprintf('| Extension Method |    OTD    | \n')
fprintf('|------------------|-----------|\n')
fprintf('|  Short signal    | %.3e |\n', mean(OTD2.rs.S))
fprintf('|  LSE extension   | %.3e |\n', mean(OTD2.rs.LSE))
fprintf('|  EDMD extension  | %.3e |\n', mean(OTD2.rs.EDMD))
fprintf('|  GPR extension   | %.3e |\n', mean(OTD2.rs.GPR))
fprintf('|__________________|___________|\n\n')